[project]
name = "apicursos"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "flask-jwt-extended>=4.7.1",
    "flask-restx>=1.3.2",
    "gunicorn>=25.0.1",
    "mongoengine>=0.29.1",
    "python-dotenv>=1.2.1",
]
